"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&rfwb2(=0!%*ib2yn5l0_8ti+!sw@*fmia^==0ub+1%_)aiao('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Adicionado para o Jazzmin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',  # Novo app de produtos
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Diretórios adicionais de arquivos estáticos
STATICFILES_DIRS = [BASE_DIR / "static"]

# Diretório de arquivos estáticos coletados (para produção)
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações do Jazzmin
JAZZMIN_SETTINGS = {
    # título da janela (será o título do painel administrativo)
    'site_title': 'CEP Admin',

    # Título na tela de login (máximo 19 caracteres)
    'site_header': 'Sistema CEP - Almoxarifado',

    # Título da marca (máximo 19 caracteres)
    'site_brand': 'CEP - ALMOXARIFADO',

    # Logo a ser usado para o site, deve estar presente nos arquivos estáticos, usado para a marca no canto superior esquerdo
    'site_logo': 'img/CEP3.png',

    # Logo específico para o formulário de login
     'login_logo': 'img/cep.png',  # Caminho relativo à pasta 'static/'

    # Ícone pequeno da aba do navegador (favicon) - idealmente 32x32px
    'site_icon': 'img/CEP2.png',  # Caminho relativo à pasta 'static/'

    # Ícones personalizados para apps e modelos
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',

        # Seus modelos (ajuste o nome do app se não for 'products')
        'products.EstoqueAtual': 'fas fa-object-group',
        'products.Entrada': 'fas fa-arrow-circle-down',
        'products.Saida': 'fas fa-arrow-circle-up',
        'products.ItemZerado': 'fas fa-exclamation-triangle',
        'products.Emprestimo': 'fas fa-handshake',
    },

    # Texto de boas-vindas na tela de login
    'welcome_sign': 'Bem-vindo(a) ao Sistema CEP - Almoxarifado',

    # Copyright no rodapé
    'copyright': 'Sistema CEP - Almoxarifado',

    # Modelos usados pela busca global
    'search_model': ['products.Peça',],

    # Mostrar ou não o personalizador de tema (se quiser ativar, descomente abaixo)
    # 'show_ui_builder': True,
}
