# Generated by Django 5.2 on 2025-04-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nossas', 'Peças nossas em poder de terceiros'), ('conserto', 'Envio de peças para conserto'), ('terceiros', 'Peças de terceiros em nosso poder')], max_length=20, verbose_name='Tipo de Empréstimo')),
                ('numero_cep', models.CharField(max_length=20, verbose_name='Nº Cep')),
                ('sp_number', models.CharField(max_length=50, verbose_name='SP Number')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('produto', models.CharField(max_length=200, verbose_name='Produto')),
                ('data', models.DateField(verbose_name='Data')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['tipo', 'produto'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cep', models.CharField(max_length=20, verbose_name='Nº Cep')),
                ('sp_number', models.CharField(max_length=50, verbose_name='SP Number')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('produto', models.CharField(max_length=200, verbose_name='Produto')),
                ('data', models.DateField(verbose_name='Data')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Entrada de Peça',
                'verbose_name_plural': 'Entradas de Peças',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cep', models.CharField(max_length=20, verbose_name='Nº Cep')),
                ('sp_number', models.CharField(max_length=50, verbose_name='SP Number')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('produto', models.CharField(max_length=200, verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Estoque Atual',
                'verbose_name_plural': 'Estoque Atual',
                'ordering': ['produto'],
            },
        ),
        migrations.CreateModel(
            name='ItemZerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cep', models.CharField(max_length=20, verbose_name='Nº Cep')),
                ('sp_number', models.CharField(max_length=50, verbose_name='SP Number')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('produto', models.CharField(max_length=200, verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Peça com Estoque Zerado',
                'verbose_name_plural': 'Peças com Estoque Zerado',
                'ordering': ['produto'],
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cep', models.CharField(max_length=20, verbose_name='Nº Cep')),
                ('sp_number', models.CharField(max_length=50, verbose_name='SP Number')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('produto', models.CharField(max_length=200, verbose_name='Produto')),
                ('data', models.DateField(verbose_name='Data')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Saída de Peça',
                'verbose_name_plural': 'Saídas de Peças',
                'ordering': ['-data'],
            },
        ),
    ]
